FROM thinkwhere/gdal-python

ENV GEOSERVER_URL=https://gaa-proxy.azurewebsites.net/geoserver
ENV API_URL=https://gaa-proxy.azurewebsites.net/api

RUN pip install geoserver-rest pyyaml validators openpyxl dataclasses
